# Generated by Django 5.1.3 on 2024-11-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_imporancia_task_importante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fecha_de_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
